### ISSUE TITLE
TreeView drag and drop when using margin-top

### ISSUE THREAD

**Issue by wilianwrech** [syncfusion/ej2-angular-ui-components#127] opened 2020-09-21 13:31 UTC
In any TreeView if you add margin-top to it, the drag and drop will have strange behaviors.
I used the example provided [here](https://ej2.syncfusion.com/angular/demos/#/material/treeview/drag-and-drop) to reproduce, I only added `style="margin-top: 40px"` to ejs-treeview element.

**Comment by PiramanayagamSyncfusion** [comment] 2020-11-15 12:16
Hi @wilianwrech ,

Sorry for the delayed response.

We are able to reproduce the reported issue (“Drag and drop misbehaves (clone element is displayed above the cursor) when specify the style (ex: margin-top as 40px) to TreeView element”) at our end and we have considered it as bug. We will include the fix for this issue in our 2020 Volume 4 release which is expected to be rolled out at end of the December 2020.

You can track this feature status in below feedback,
https://www.syncfusion.com/feedback/19701/drag-and-drop-malfunction-when-setting-tap-margin

We appreciate your patience.

Regards,
Piramanayagam R

**Comment by PiramanayagamSyncfusion** [comment] 2020-12-24 12:53
Hi @wilianwrech ,

Sorry for the inconvenience. 
 
Due to some technical difficulties, we were unable to include the fix in Volume 4 release, 2020. We are working on this with high priority. 
  
We will include this fix in 2020 Volume 4 SP release which is expected to be rolled out by the end of January 2021. 
  
We appreciate your patience.

Regards,
Piramanayagam R

**Comment by PiramanayagamSyncfusion** [comment] 2021-03-30 09:42
Hi @wilianwrech ,

We deeply regret for the inconvenience.

Due to some technical difficulties, we were unable to include this fix in Volume 4 SP release, 2020. 

We will include this fix in 2021 Volume 1 SP release which is expected to be rolled out by the end of April 2021.

We appreciate your patience.

Regards,
Piramanayagam R

**Comment by PiramanayagamSyncfusion** [comment] 2021-07-09 14:59
Hi @wilianwrech ,

Sorry for the delay.

You can resolve the reported issue by using internal CSS instead of the inline CSS. Please refer to the below code,
`<style>
  .e-treeview {
    margin-top: 40px;
  }
</style>
`

For your reference, we have modified your sample based on this in the link: https://stackblitz.com/edit/angular-bezb4g-w2lbwx?file=app.component.html

Please let us know if you need further assistance on this.

Regards,
Piramanayagam R

**Closed** 2021-07-09 15:01 UTC
Labels: bug, treeview
