### ISSUE TITLE
Context Menu Elements are not removed after the component is destroyed

### ISSUE THREAD

**Issue by hinhle** [syncfusion/ej2-angular-ui-components#196] opened 2021-09-28 07:39 UTC
Dear Team,

I found out that the context menu elements and some other elements of the angular document editor container were not destroyed or removed even after the component containing the editor component had already been destroyed.

![image](https://user-images.githubusercontent.com/56920722/135043819-78c3771d-7812-4483-b369-d76820aa4b54.png)
The first image describes the context menu when I open the component containing the editor at the first time
![image](https://user-images.githubusercontent.com/56920722/135043871-9d8f8b08-fcd1-4927-a69c-745c60fbf47c.png)
The second image describes the context menu when I open the component at the second time.
The context menu still appears even though the component is destroyed.

Thank you.

**Comment by hinhle** [comment] 2021-09-28 10:02
I downgraded the lib version to 19.2.59 and the app works fine.

**Comment by Suriya-Murugan** [comment] 2021-09-29 07:16
Hi Hinhle,

Syncfusion Geetings!

We couldn’t reproduce the reported issue. Please check below sample in which we handled destroy.

https://stackblitz.com/edit/angular-ezfybu?file=app.component.ts

Can you please modify and share the above sample to recreate the same issue our side and if possible, share video illustration? so that we can proceed further and provide you solution at earliest.

Regards,
Suriya M.

**Comment by mtschneiders** [comment] 2021-11-03 13:09
I reported this issue to Syncfusion and they seem to have fixed it in the latest version (19.3.48).
Here's the bug report: [link](https://www.syncfusion.com/feedback/29554/context-menu-issue-after-rendering-multiple-instances-of-documenteditor-in-the)

**Comment by syncsiva** [comment] 2022-02-02 12:34
Closing the issue since its been fixed already.

**Closed by syncsiva** 2022-02-02 12:34 UTC
Labels: word-processor
