### ISSUE TITLE
Scheduler control Agenda View locks up the browser tab when multi-day event has non-zero milliseconds set

### ISSUE THREAD

**Issue by jcgillespie** [syncfusion/ej2-angular-ui-components#115] opened 2020-08-11 13:58 UTC
If a multi-day appointment has a non-zero millisecond value in the EndTime value, it causes the browser to lock up and eventually die.

Here's a [stackblitz](https://stackblitz.com/edit/angular-vgyukv?file=data.ts) repro based on a stripped down version of the Scheduler demo.

There are two events in the dataset. The only difference between them is the "day" on the EndTime value.
If you uncomment the second event in the dataset, it will lock up.

**Comment by VengateshManiraj** [comment] 2020-09-03 05:05
We have validated your reported query “Schedule freezes in Agenda view when a spanned event presents with the EndTime value of non-zero milliseconds” at our end. We are able to reproduce the issue that you have reported and logged the defect report at our end and the fix will be included in our weekly patch release which is scheduled to be rolled out by September 09, 2020. You can track this defect status in the below feedback link.

Feedback: https://www.syncfusion.com/feedback/16966/schedule-freezes-in-the-agenda-view-when-an-spanned-event-present-with-an-endtime

**Comment by vinithadevi** [comment] 2020-09-09 10:59
Dear Customer,

Thanks for your patience.

We are glad to announce that our Essential Javascript2 patch release (v18.2.57) has been rolled out successfully and in that release we have added the fix for “Schedule freezes in Agenda view when a spanned event presents with the EndTime value of non-zero milliseconds” issue. So please update your package to this version to include the fix. 
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 

Feedback link: https://www.syncfusion.com/feedback/16966/schedule-freezes-in-the-agenda-view-when-an-spanned-event-present-with-an-endtime

Regards,
Vinitha

**Comment by ajithr** [comment] 2020-12-02 12:53
We are closing this issue since there is no recent activity. Feel free to reopen this and update your comments for the reinvestigation.

**Closed by ajithr** 2020-12-02 12:53 UTC
Labels: schedule
