### ISSUE TITLE
Dropdown list inside scrollable area

### ISSUE THREAD

**Issue by mkvlpl** [syncfusion/ej2-angular-ui-components#54] opened 2019-08-29 13:11 UTC
When scrolling the parent of a dropdown list in open state, the list moves to follow the anchor element. It keeps moving when anchor is scrolled out of visible area which looks bad.

Shouldn't it disappar/close in such case? Or maybe behave like native select element where list disappears on scroll?

Example:

https://stackblitz.com/edit/angular-qkainc

![example](https://i.imgur.com/XbQthhH.gif)

**Comment by sevvandhi** [comment] 2019-08-30 12:08
Hi Mkvlpl, 

Greetings from Syncfusion support.

We are validating the reported issue. We will update further details within 2 business days(4th September 2019). Until then, we appreciate your patience.

Regards,
Sevvandhi N

**Comment by sevvandhi** [comment] 2019-09-05 05:48
Hi Mkvlpl,

Thanks for the patience.

We are confirmed the  reported issue as a bug at our end. And the fix will be included in our volume  3 release which is expected to be rolled out on end of September 2019. Until then, we appreciate your patience.

You can now track the reported issue from the below feedback link,

**Feedback link:** https://www.syncfusion.com/feedback/8666/popup-remains-visible-even-when-the-target-element-is-hidden-in-the-view

Regards,
Sevvandhi N

**Comment by mkvlpl** [comment] 2019-09-23 07:49
Hello,

I can see that you released the 2019 vol 3 beta last Friday.

Going through [release notes](https://ej2.syncfusion.com/angular/documentation/release-notes/17.3.9/) and looking quickly at code changes I can't see any fix for this bug. Is it included? If not, when can we expect it to be?

**Comment by sevvandhi** [comment] 2019-10-05 11:14
Hi Mkvlpl,

Sorry for the inconvenience caused.

Due to complexity, the fix was not included in volume 3 release. We will provide high priority and include the fix in **October's 2nd patch release** which is expected to be rolled in mid of October. We appreciate your patience until then.

 Regards,
 Sevvandhi N

**Comment by saravanangn** [comment] 2019-11-08 10:40
Hi Michal,

Thanks for the patience. 

We are glad to announce that our latest release in the version 17.3.20 has been rolled out successfully and in that release, we have included the “Popup remains visible even when the target element is hidden in the view”.  So, we suggest you upgrade our Syncfusion packages to our latest version to resolve this issue in your end. 
Please find the release notes details from the below link. 

Release notes: [https://ej2.syncfusion.com/angular/documentation/release-notes/17.3.19/#dropdownlist ](url)

Regards,
Saravanan G

**Comment by ajithr** [comment] 2020-07-15 10:36
We are closing this issue since there is no recent activity. Feel free to reopen the issue and update your comments for the reinvestigation.

**Closed by ajithr** 2020-07-15 10:36 UTC
Labels: bug, dropdown-list
