### ISSUE TITLE
Rich Text Editor:  Copy paste from ms word not working

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#204] opened 2021-11-12 12:22 UTC
Dear Team,
Copy paste from Ms word from not working.
Please find error code images.

We are forced to use other Rich text editor.
Error code
DOMException: Failed to execute 'setStart' on 'Range': The offset 1 is larger than the node's length (0). syncfusion richtexteditor

ERROR TypeError: Cannot read properties of undefined (reading 'parentNode')
    at Function.getImmediateBlockNode (0.8046d1dca75a5b402897.js:1)
    at Function.insertTempNode (0.8046d1dca75a5b402897.js:1)
    at Function.pasteInsertHTML (0.8046d1dca75a5b402897.js:1)
    at Function.Insert (0.8046d1dca75a5b402897.js:1)
    at wv.applyHtml (0.8046d1dca75a5b402897.js:1)
    at G.notify (0.8046d1dca75a5b402897.js:1)
    at Dv.execCommand (0.8046d1dca75a5b402897.js:1)
    at useValue.formatting (0.8046d1dca75a5b402897.js:1)
    at useValue.selectFormatting (0.8046d1dca75a5b402897.js:1)
    at dt.click (0.8046d1dca75a5b402897.js:1)

**Comment by VinithaJeyakumar** [comment] 2022-02-03 10:20
Hi Arun,


We have tried to reproduce the reported issue by copying and pasting some texts from MS word to Rich Text Editor. but we didn't face any console errors. we have also prepared a sample and video illustration for your reference.

**Sample**: https://stackblitz.com/edit/angular-axyypo?file=app.component.ts

**Video illustration:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/RTE_MS269950085

Can you please share the following details to further validate on the issue?

- Your package version.
- Exact issue reproducing steps.
- Video illustration of issue replication steps.
- If possible, please share us with the runnable issue reproducing sample or modify the attached sample with the issue replicating code.

Please ensure the issue after updating to the latest version.

Regards,
Vinitha

**Comment by gsumankumar** [comment] 2022-02-22 05:03
We have closed this issue, since there's no recent activities. If the provided sample is not helpful or still the issue is reproducing, please feel free to reopen it.

**Closed by gsumankumar** 2022-02-22 05:03 UTC
Labels: rich-text-editor
