### ISSUE TITLE
Date range picker is not responding on chrome in tablet or mobile mode after opening calendar dropdown

### ISSUE THREAD

**Issue by shivam11gupta** [syncfusion/ej2-angular-ui-components#68] opened 2019-10-05 19:51 UTC
daterangepicker.js:3173 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by BerlyChristopher** [comment] 2019-10-08 11:52
Hi Shivam,

Greetings from Syncfusion support. 

We have confirmed the reported issue as a bug at our end and this fix will be included in our patch release scheduled on **23rd October 2019**. We appreciate your patience until then. You can track the status of the reported issue from the below feedback link.

**Feedback Link**: https://www.syncfusion.com/feedback/9351/while-select-the-value-in-the-daterangepicker-popup-in-mobile-mode-script-error-is

Regards,
Berly B.C

**Comment by BerlyChristopher** [comment] 2019-10-23 16:38
Hi Shivam,

Currently, we are validating the fix with existing cases. We will move this fix in our Volume 3 SP1 release, which will be expected to roll out by the first week of November.

Regards,
Berly B.C

**Comment by Sureshkumar2288** [comment] 2019-11-21 06:44
HI Shivam,

We are glad to announce that our latest release in the version V17.3.27 has been rolled out successfully and in that release, we have included the “**While select the value in the DateRangePicker popup in mobile mode script error is thrown**”.  So, we suggest you upgrade our Syncfusion packages to our latest version to resolve this issue in your end.  
   
Please find the sample and release notes details from the below link.  
   
Sample Link: https://stackblitz.com/edit/angular-xhrpk9-eucmkh?file=app.component.html   
   
Release notes: https://ej2.syncfusion.com/angular/documentation/release-notes/17.3.27/#daterangepicker 

Regards,
Sureshkumar P

**Comment by ajithr** [comment] 2020-07-15 10:35
We are closing this issue since there is no recent activity. Feel free to reopen the issue and update your comments for the reinvestigation.

**Closed by ajithr** 2020-07-15 10:35 UTC
Labels: bug, date-range-picker
