### ISSUE TITLE
ej2-angular-richtexteditor throwing following error on specific template data

### ISSUE THREAD

**Issue by gauravbabu74** [syncfusion/ej2-angular-ui-components#92] opened 2020-02-28 07:40 UTC
core.js:6014 ERROR TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at Table.calcPos (ej2-richtexteditor.es2015.js:17937)
    at Table.tableResizeEleCreation (ej2-richtexteditor.es2015.js:17908)
    at Table.resizeHelper (ej2-richtexteditor.es2015.js:17876)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:465)
    at invokeTask (zone-evergreen.js:1603)
    at HTMLDivElement.globalZoneAwareCallback (zone-evergreen.js:1629)

Use following HTML 👍 
<table border="0" cellpadding="0" cellspacing="0" align="center">
  <tbody><tr>
    <td style="width:556px; background-color:f8f8f8" bgcolor="f8f8f8">
    <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="border:1px solid #e9e9e9; background-color:#f8f8f8;">
    <tbody><tr>
        
          <td style="padding:0px 4.5%;">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
          
          <tbody><tr>
                <td style="margin:0px; padding:22px 0px;" valign="top" align="center" class=""><br></td>
              </tr>
              
              <tr>
                <td style="padding:27px 18px 0px 22px;font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;" class="">
                <strong>Hi {{{name}}},</strong><br><br>

 
 Welcome to . My name is.
 
              
              </td>
              </tr>
              
              <tr>
                <td style="padding:10px 18px 30px 22px;font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;" class=""><br></td>
              </tr>
              
              <tr>
                <td style="margin:0px; padding:0px; background-color:#ffffff;" valign="top" bg="#ffffff" class="">
                <a href="{{{siteurl}}}/login" style="text-decoration:none; outline:none;"> </a></td>
              </tr>
              
              <tr>
                <td style="padding:20px 20px 2px;font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#2a363b; line-height:20px; text-align:center; background-color:#ffffff;" bgcolor="#ffffff"> Username: <strong>
               {{{username}}} </strong></td>
              </tr>
              
              <tr>
                <td style="padding:0px 20px 5px;font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#2a363b; line-height:20px; text-align:center; background-color:#ffffff;" bgcolor="#ffffff"> Password: <strong>{{{password}}}</strong></td>
              </tr>
              
              <tr>
                <td style="margin:0px; padding:5px 0px 20px;text-align:center;background-color:#ffffff;" bgcolor="#ffffff" valign="top" class=""><a href="{{{siteurl}}}/login" style="text-decoration:none; outline:none;">  </a></td>
              </tr>
              
              
              <tr>
              
                       
              </tr><tr>
                <td style="padding:22px 18px 0px 22px; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;" class="">Should you forget your password,&nbsp;</td>
              </tr> 
              
              <tr>
                <td style="padding:15px 18px 22px 22px;font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;" class="">I'm also going to try</td>
              </tr>        
              
              
              
              <tr>
                <td style="padding:20px 0px;">
                <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color:rgba(93, 93, 93, 0.13); width:100%; padding:6px 22px 16px;" bgcolor="e4e4e4">
  <tbody><tr>
    <td>

                     <table width="220" border="0" align="left" cellpadding="0" cellspacing="0">
                    <tbody>
                      <tr>
                        <td style="padding:10px 0px 0px; margin:0px;font-family:Arial, Helvetica, sans-serif; font-size:12px; line-height:20px; color:#2a363b">{{{signature}}}<br>
                          {{{mailFooter}}}

                          </td>
               
       
            
                      </tr>
                    </tbody>
                  </table>
                  
                  </td>
  </tr>
</tbody></table>
                  
                  </td>
              </tr>
                            
            </tbody></table>
            </td>
            </tr>
      </tbody></table></td>
  </tr>
</tbody></table>

**Comment by NarayanasamyP** [comment] 2020-03-02 14:24
Hi @gauravbabu74 ,

Good day to you.

It seems the shared code example is not clear to reproduce your issue. It is possible to share your code example as an attachment or through any other online editor to your template code(stackBlitz), it will be easy to reproduce your issue.

You can paste the code for template part and revert back to us from the below link: https://stackblitz.com/edit/angular-prf4dg-3r3loo[editable demo]

Regards,
Narayanasamy P.

**Comment by gauravbabu74** [comment] 2020-03-04 06:27
<table border="0" cellpadding="0" cellspacing="0" align="center">
   <tbody>
      <tr>
         <td style="width:556px; background-color:f8f8f8" bgcolor="f8f8f8">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="border:1px solid #e9e9e9; background-color:#f8f8f8;">
               <tbody>
                  <tr>
                     <td style="padding:0px 4.5%;">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                           <tbody>
                              <tr>
                                 <td style="margin:0px; padding:22px 0px;" valign="top" align="center"><a href="#" style="text-decoration:none; outline:none;"> <img src="#" alt="" style="margin:0px; padding:0px;"></a></td>
                              </tr>
                              <tr>
                                 <td style="padding:27px 18px 0px 22px;font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;">
                                    <strong>Hi</strong><br><br>
                                    Test Data
                                 </td>
                              </tr>
                              <tr>
                                 <td style="padding:10px 18px 30px 22px;font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;">
                                    Test data
                                 </td>
                              </tr>
                              <tr>
                                 <td style="margin:0px; padding:0px; background-color:#ffffff;" valign="top" bg="#ffffff">
                                    <a href="#" style="text-decoration:none; outline:none;"> <img src="#" width="100%" alt="test" style="margin:0px; padding:0px;"></a>
                                 </td>
                              </tr>
                              <tr>
                                 <td style="padding:20px 20px 2px;font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#2a363b; line-height:20px; text-align:center; background-color:#ffffff;" bgcolor="#ffffff"> Username: <strong>
                                    </strong>
                                 </td>
                              </tr>
                              <tr>
                                 <td style="padding:0px 20px 5px;font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#2a363b; line-height:20px; text-align:center; background-color:#ffffff;" bgcolor="#ffffff"> Password: <strong>{{{password}}}</strong></td>
                              </tr>
                              <tr>
                                 <td style="margin:0px; padding:5px 0px 20px;text-align:center;background-color:#ffffff;" bgcolor="#ffffff" valign="top"><a href="#" style="text-decoration:none; outline:none;"> <img src="https://cdn.b2cdev.com/images-mail/click-here-sign.png" style="margin:0px; padding:0px;" alt="Click Here Sign"> </a></td>
                              </tr>
                              <tr>
                              </tr>
                              <tr>
                                 <td style="padding:22px 18px 0px 22px; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;">Should you forget your password, simply click the <strong><a href="{{{siteurl}}}/index.php?option=com_login&amp;task=lostPassword&amp;Itemid=518" style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; text-decoration:underline">"Forgot Password?"</a></strong> link on the login page <strong><a href="" style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; text-decoration:underline">tests
                                    </a></strong>
                                 </td>
                              </tr>
                              <tr>
                                 <td style="padding:15px 18px 22px 22px;font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#2a363b; line-height:20px; background-color:#ffffff;">test</td>
                              </tr>
                              <tr>
                                 <td style="padding:20px 0px;">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color:rgba(93, 93, 93, 0.13); width:100%; padding:6px 22px 16px;" bgcolor="e4e4e4">
                                       <tbody>
                                          <tr>
                                             <td>
                                                <table width="220" border="0" align="left" cellpadding="0" cellspacing="0">
                                                   <tbody>
                                                      <tr>
                                                         <td style="padding:10px 0px 0px; margin:0px;font-family:Arial, Helvetica, sans-serif; font-size:12px; line-height:20px; color:#2a363b">{{{signature}}}<br>
                                                         </td>
                                                      </tr>
                                                   </tbody>
                                                </table>
                                             </td>
                                          </tr>
                                       </tbody>
                                    </table>
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                     </td>
                  </tr>
               </tbody>
            </table>
         </td>
      </tr>
   </tbody>
</table>

**Comment by gauravbabu74** [comment] 2020-03-04 06:28
Please use above html for editor and check console to see errors.

**Comment by NarayanasamyP** [comment] 2020-03-04 12:12
Hi Gauravbabu,

Thanks for your update.

We have validated the reported issue and we confirmed it as a defect from our end. Fix for the reported issue will be included in the upcoming volume-1 release, which is expected to roll out at the end of March 2020. 

Now you can track the status of the defect from the following feedback link: https://www.syncfusion.com/feedback/12503




Regards,
Narayanasamy P.

**Comment by Indrajith-Sync** [comment] 2020-04-01 14:21
Hi @gauravbabu74 ,

Thanks for your patience,

Due to improper usage of template content, this issue occurs. The content used, is not a valid HTML format hence it throws script error with Rich Text Editor. Below is the correct usage of the templates.

`Sample: https://stackblitz.com/edit/angular-prf4dg-lyco8e?file=app.component.html`

Can you please check the above solution and let us know if you it meets your requirements?

Regards,
Indrajith

**Comment by rajendranr-5483** [comment] 2020-07-22 06:28
@gauravbabu74 ,

Have you checked the sample which we shared in the previous update? 

We are closing this thread now. Reopen this thread if any concerns.

**Closed** 2020-07-22 07:30 UTC
Labels: rich-text-editor
