### ISSUE TITLE
Error when setting tsconfig target to ES6. 

### ISSUE THREAD

**Issue by kyro38** [syncfusion/ej2-angular-ui-components#30] opened 2019-06-12 09:58 UTC
I'm getting the following error when I set my` tsconfig.json`  to `"target": "es6"`  : 

```
 Class constructor DocumentEditorContainer cannot be invoked without 'new'
    at new DocumentEditorContainerComponent
```

That happens when I instanciate a component that uses the Document editor

**Comment by RamyaThiru** [comment] 2019-06-13 10:41
Hi , 
 
We can reproduce the reported issue with document editor and es 6. This reported problem is a bug in Angular CLI, and we have already reported it to them. For further information, you can refer to the link as below.

Link: https://github.com/angular/angular-cli/issues/14717
  
We will update you once angular team published the changes and after ensured it in our end. We are not able to give exact timeline since it depends on the angular package publish.  
 
Until then we suggest you use “es5” as target.  
 
Regards, 
Ramya T

**Comment by kumaresan-subramani** [comment] 2019-08-06 09:20
Hi,

Reported issue got resolved in angular version 8.2.0.

https://github.com/angular/angular-cli/issues/14717

**Comment by kyro38** [comment] 2019-08-21 13:00
The problem is not solved for me.

**Comment by dskesavan** [comment] 2019-08-27 09:55
Hi @kyro38 ,

Sorry for the inconvenience caused.

The problem faced when using target as "es6" with latest Angular CLI 8.2.2 requires changes in our packages. Currently we are working to fix the issue and the fix will be available in our upcoming EJ2-Patch release on September 3rd 2019.

Regards,
Kesavan.

**Comment by kyro38** [comment] 2019-10-16 15:16
The editor works great when building (debug build) with target ES6 but break on a prod build. 

After a prod build it throws the following error : `TypeError: Cannot read property 'spellCheck' of undefined`

**Comment by MugunthanAnbalagan** [comment] 2019-10-26 04:14
Hi @kyro38,

We have tried to replicate the reported issue but unfortunately we are unable to reproduce the issue from our side. So, we suspect this might occurs do to sample code used in your side.
 
Please find the sample code we have used to replicate the reported issue below.

`import { Component, ViewChild } from '@angular/core';
import { ToolbarService, DocumentEditorContainerComponent } from '@syncfusion/ej2-angular-documenteditor';
@Component({
  selector: 'app-root',
  template: `
<h1>
    Hello Angular, Syncfusion Angular UI Button!
 </h1>
 <div>
 <ejs-documenteditorcontainer #documenteditor_default [enableToolbar]=true (created)="created()" style="display:block;height:600px"></ejs-documenteditorcontainer>
</div>
 `,
  providers: [ToolbarService]
})
export class AppComponent {
  @ViewChild('documenteditor_default', { static: false })
  public container: DocumentEditorContainerComponent;
  public created(): void {
    var settings = { import: 'Import1', systemClipboard: 'SystemClipboard1', spellCheck: 'SpellCheck1', restrictEditing: 'RestrictEditing1' }
    this.container.serverActionSettings = settings;
  }
}
`

So, kindly share us the sample code and tsconfig used in your project to reproduce the issue in our side which will helpful for us to investigate on it and provide you the appropriate solution at the earliest.

Regards,
Mugunthan A

**Comment by ajithr** [comment] 2020-12-02 12:20
We are closing this thread since there is no recent activity. Feel free to reopen the issue and update your comments for the reinvestigation.

**Closed by ajithr** 2020-12-02 12:20 UTC
Labels: bug, common, word-processor
