### ISSUE TITLE
DropdwonList moves on page-scrolling

### ISSUE THREAD

**Issue by bleazee** [syncfusion/ej2-angular-ui-components#11] opened 2019-03-01 15:06 UTC
Expected Behaviour:
The Dropdownlist sticks to the input-field you opened it from, while scrolling the page

Actual Behaviour:
The Dropdownlist moves with the whole page while scrolling

Live-behaviour from a gif:

![dropdownlist issue](https://user-images.githubusercontent.com/24584971/53645991-69a98d80-3c3a-11e9-822c-3d397ee5f2d9.gif)

I noticed it was the css "top" property, which caused it to stick while scrolling, but I could not get a solution to this, as the top-property gets set by your controls i think.

I also checked and made a comparison with your following demo: 
https://ej2.syncfusion.com/angular/demos/#/material/multi-select/checkbox

CSS looks exactly alike in both examples.

**Comment by PrinceOliver** [comment] 2019-03-05 04:15
Hi @bleazee ,

Thank you for using Syncfusion products.

We have validated your reported scenario in our end. But unfortunately, we were unable to replicate the reported behavior in our end. We suspect that this might have occurred due to some of your CSS files which were used in your project could be overriding any style of the multiselect control.  We have prepared a test sample to check this behavior in our end, please find the test sample in the following location for your reference

Sample Link: https://stackblitz.com/edit/angular-2x475k

Kindly check the above sample and If you are still facing the problem, please share the following details.

•	Share the CSS files which are used in your application.

•	Share the exact scenario/proper replication procedure sufficient to replicate the issue.

•	Share your dropdowns package version, machine and browser details

•	If possible, kindly modify the attached test sample to reproduce the issue.

The above details will help us isolate the root cause of the issue and provide a prompt solution at the earliest. Thank you for your time and cooperation in advance.

Regards,
Prince

**Comment by bleazee** [comment] 2019-03-05 10:44
Hello @PrinceOliver ,

I'll try to provide as much information as possible:

Versions & Packages:

- @syncfusion/ej2-angular-dropdowns: 16.4.44 (also tried with 16.4.55)

- Google Chrome: Version 72.0.3626.121 64-Bit

- Firefox: 65.0.2 64-Bit

- MS Edge: 42.17134.1.0

- OS: Windows 10 Enterprise (x64)

Our custom CSS-File for the changes on your multiselect:
```

// Dropdown not open:
.e-multiselect.e-input-group.e-checkbox {
  height: 26px;

  &:active {
    border-color: $wcr-primary-border-color;
    background-color: $wcr-primary-selection-text-color;
    color: $wcr-primary-font-color;
  }

  &:focus {
    border-color: $wcr-primary-input-hovered-border;
    background-color: $wcr-primary-input-background-color;
    color: $wcr-primary-font-color;
  }

  &:hover {
    border-color: $wcr-primary-input-hovered-border;
    color: $wcr-primary-font-color;
  }

  &::selection {
    background-color: $wcr-primary-selection-background-color;
    color: $wcr-primary-selection-text-color;
  }

  .e-multi-select-wrapper {
    min-height: 26px;

    .e-searcher {
      height: 26px;
    }

    input[type="text"] {
      height: 26px;
      min-height: 26px;
    }

    .e-chips-close.e-close-hooker {
      padding-top: 5px;
      padding-left: 10px;
    }

    .e-input-group-icon.e-ddl-icon {
      height: 22px;
      min-height: 22px;
      padding-top: 2px;
    }

    .e-delim-values {
      font-family: $wcr-font-family;
      font-size: $wcr-font-size-base;
      height: 26px;
      line-height: 25px;

      .e-remain {
        line-height: 9px;
        font-size: 12px;
      }
    }

    .e-delim-view.e-delim-values {
      max-width: max-content;
    }

    @supports (-ms-ime-align:auto) {
      .e-delim-view.e-delim-values {
        max-width: 80%;
      }
    }
  }
}

// DropDown open part
.e-ddl.e-popup.e-multi-select-list-wrapper.e-checkbox.e-lib.e-control.e-popup-open {
  .e-input-group.e-control-wrapper {
    border: none;

    .e-input-filter.e-input {
      border: 1px solid $wcr-primary-selection-text-color;
      background-color: $wcr-primary-selection-text-color;
      color: $wcr-primary-font-color;

      &:hover {
        border-color: $wcr-primary-input-hovered-border;
        background-color: $wcr-primary-selection-text-color;
        color: $wcr-primary-font-color;
      }

      &::selection {
        border-color: $wcr-primary-border-color;
        background-color: $wcr-primary-input-background-color;
        color: $wcr-primary-font-color;
      }
    }
  }

  .e-dropdownbase {
    .e-list-item {
      background-color: $wcr-primary-selection-text-color;

      &.e-active {
        background-color: $wcr-primary-input-background-color;

        &.e-item-focus {
          background-color: $wcr-primary-input-background-color;
          border: 1px solid $wcr-primary-inactive-text-color;
        }
      }

      &.e-item-focus {
        background-color: $wcr-primary-selection-text-color;
        border: 1px solid $wcr-primary-inactive-text-color;
      }

      &:hover {
        background-color: $wcr-primary-selection-text-color;
        border: 1px solid $wcr-primary-input-hovered-border;
      }
    }
  }

  // Checkbox in the DropDown
  .e-frame.e-icons {
    border-color: $wcr-primary-font-color;
    background-color: $wcr-primary-selection-text-color;

    &.e-check {
      color: $wcr-primary-font-color;
    }
  }

  // Select All in the DropDown
  .e-selectall-parent {
    font-weight: bold !important;

    .e-frame.e-icons {
      margin-bottom: 3px;
    }
  }
}
```
Excact Scenario:

When I click on the multiselect-input-field the dropdown opens as expected. As soon as I start scrolling I would expect the Dropdown to stick to the multiselect-input-field like in your example provided. Instead the dropdown moves along with the page when im scrolling, resulting in an ugly sight and also bad user experience.
I tried to replicate this behaviour several times with one of your examples as the base but i couldn't manage to copy it in your example.

I originally thought that maybe our nested containers are giving the multiselect issues with its positioning but I also tried to change every "position" or "display"-property of our div-containers and still, nothing changed. Are there other properties which can cause issues with the dropdowns positioning or behaviour? 

Thank you for your time and effort.
Regards,
bleazee

**Comment by PrinceOliver** [comment] 2019-03-06 12:07
Hi @bleazee, 

Thank you for your update.

We could replicate the reported issue in our end with the provided details. We have validated the reported issue and we are considering this as a defect in our end. The fix for the reported issue will be included in our upcoming 2019 Volume 1 main release which is scheduled to be rolled on March 2019. You can now track the current status of your request, review the proposed resolution timeline, and contact us for any further inquiries through this link: https://www.syncfusion.com/feedback/5082/         

Regards,
Prince

**Comment by PrinceOliver** [comment] 2019-04-02 04:19
Hi @bleazee ,

We are glad to announce that our Essential Studio Volume 1, 2019 release (v17.1.0.38) is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/143619/essential-studio-2019-volume-1-release-v17-1-0-38-is-available-for-download

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Prince

**Comment by Sridhar-Narasimhan** [comment] 2019-10-23 11:38
Closing the issue due to inactivity for a long time and solution already provided.

**Closed by Sridhar-Narasimhan** 2019-10-23 11:38 UTC
